apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-config
  labels:
    {{- include "health-monitor.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
